import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const tsDir = join(repoRoot, "contracts", "generated", "ts");
const rustDir = join(repoRoot, "contracts", "generated", "rust");

const DOMAINS = ["cli", "core", "installer", "kernel", "planner", "providers", "runtime", "skills"];

const read = (dir: string, file: string) => readFileSync(join(dir, file), "utf8");

describe("contracts generator", () => {
  it("regenerates deterministically with no drift", () => {
    const before = new Map(
      readdirSync(tsDir).map((f) => [`ts/${f}`, read(tsDir, f)] as const),
    );
    for (const f of readdirSync(rustDir)) before.set(`rust/${f}`, read(rustDir, f));

    execFileSync(process.execPath, [join(repoRoot, "tools", "gen-contracts.mjs")], {
      cwd: repoRoot,
    });

    for (const [key, content] of before) {
      const [kind, file] = key.split("/");
      expect(read(kind === "ts" ? tsDir : rustDir, file!)).toBe(content);
    }
  });

  it("emits every domain module plus barrels", () => {
    const tsFiles = readdirSync(tsDir).sort();
    const rustFiles = readdirSync(rustDir).sort();
    expect(tsFiles).toEqual([...DOMAINS.map((d) => `${d}.ts`), "index.ts"].sort());
    expect(rustFiles).toEqual([...DOMAINS.map((d) => `${d}.rs`), "mod.rs"].sort());
  });

  it("barrel files export all domain modules", () => {
    const tsBarrel = read(tsDir, "index.ts");
    const rustBarrel = read(rustDir, "mod.rs");
    for (const domain of DOMAINS) {
      expect(tsBarrel).toContain(`export * from "./${domain}.js";`);
      expect(rustBarrel).toContain(`pub mod ${domain};`);
    }
  });

  it("generated files carry the header and no dynamic or machine-local content", () => {
    for (const dir of [tsDir, rustDir]) {
      for (const file of readdirSync(dir)) {
        const content = read(dir, file);
        expect(content.startsWith("// This file is generated by tools/gen-contracts.mjs.")).toBe(
          true,
        );
        expect(content).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/);
        expect(content).not.toMatch(/\/Users\/|\/home\/|[A-Z]:\\/);
      }
    }
  });

  it("TypeScript output includes representative contract types", () => {
    expect(read(tsDir, "core.ts")).toContain("export interface KernelWarning");
    expect(read(tsDir, "kernel.ts")).toContain("export type ReleaseState");
    expect(read(tsDir, "kernel.ts")).toContain("export interface ValidationReport");
    expect(read(tsDir, "planner.ts")).toContain("export interface TaskGraph");
    expect(read(tsDir, "providers.ts")).toContain("export type ProviderId");
    expect(read(tsDir, "skills.ts")).toContain("export type SkillId");
    expect(read(tsDir, "cli.ts")).toContain("export interface CliJsonOutput");
    expect(read(tsDir, "installer.ts")).toContain("export interface InstallManifest");
  });

  it("TypeScript unions are discriminated by their string tag", () => {
    const core = read(tsDir, "core.ts");
    expect(core).toContain("export type KernelResult = KernelResultOk | KernelResultErr;");
    expect(core).toContain('status: "ok";');
    expect(core).toContain('status: "error";');
  });

  it("Rust output includes representative contract types", () => {
    expect(read(rustDir, "core.rs")).toContain("pub struct KernelWarning");
    expect(read(rustDir, "kernel.rs")).toContain("pub enum ReleaseState");
    expect(read(rustDir, "kernel.rs")).toContain("pub struct ValidationReport");
    expect(read(rustDir, "planner.rs")).toContain("pub struct TaskGraph");
    expect(read(rustDir, "providers.rs")).toContain("pub enum ProviderId");
    expect(read(rustDir, "skills.rs")).toContain("pub enum SkillId");
    expect(read(rustDir, "cli.rs")).toContain("pub struct CliJsonOutput");
    expect(read(rustDir, "installer.rs")).toContain("pub struct InstallManifest");
  });

  it("Rust unions use serde string tags", () => {
    const core = read(rustDir, "core.rs");
    expect(core).toContain('#[serde(tag = "status")]');
    expect(core).toContain('#[serde(rename = "ok", rename_all = "camelCase")]');
  });
});
